name: build-and-test

on:
  push:
    # all branches
  pull_request:
    branches:
      - main
      - master

  # This enables the Run Workflow button on the Actions tab.
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: dylan-lang/install-opendylan@v2

      - name: test and install
        env:
          DYLAN_CATALOG: ext/pacman-catalog
          DYLAN: dylan-root
        run: |
          make test
          make install

      - name: Exercise dylan-tool
        env:
          DYLAN_CATALOG: ext/pacman-catalog
          DYLAN: dylan-root
        run: |
          ${DYLAN}/bin/dylan new workspace test-workspace
          cd test-workspace
          ${DYLAN}/bin/dylan new library abc strings@1.1
          ${DYLAN}/bin/dylan update
          ${DYLAN}/bin/dylan status
          ${DYLAN}/bin/dylan list
          ../dylan-compiler -build abc-test-suite
          _build/bin/abc-test-suite
